repos:
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
        - --disable=C0114
        - --fail-under= 7

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black

- repo: local
  hooks:
  - id: unittest
    name: unittest
    entry: python -m unittest discover -s test
    language: python
    'types': [python]
    additional_dependencies: [requests, signalrcore, pyodbc]
    pass_filenames: false
    stages: [commit]
    