apiVersion: v1
clusters:
- cluster:
    server: http://localhost:8080
  name: local
contexts:
- context:
    cluster: local
  name: local
current-context: local
kind: Config
preferences: {}
users:
- name: local
